# Special Numbers
ACKNOWLEDGE_BIT = b"\x08"
TERMINATE_BIT = b"\x07"
DONT_CARE_BITS = b"\x00\x00\x00\x00\x00"
ALTER_METER_SETT_BIT = b"\x0e"
ALTER_STREAM_PERIOD_BIT = b"\x0f"
TABLE_HEADERS_COUNT = 5  # per props cmd

# Identification Commands
ID_METER_PROP_CMD = b"\x01" + DONT_CARE_BITS
ID_METER_SETT_CMD = b"\x02" + DONT_CARE_BITS

# Stream, Time, and Reset Commands
STREAM_DATA_CMD = b"\x03" + DONT_CARE_BITS
RESET_TIME_CMD = b"\x04" + DONT_CARE_BITS

# General Communication Commands
TERMINATE_CMD = TERMINATE_BIT + DONT_CARE_BITS
ACKNOWLEDGE_CMD = ACKNOWLEDGE_BIT + DONT_CARE_BITS
NULL_ACTION_CMD = b"\x00" + DONT_CARE_BITS
KILL_ALL_PROCESS_CMD = b"\xff" + DONT_CARE_BITS

# Flash Chip Access Commands
FILE_DIRECTORY_CMD = b"\x05" + DONT_CARE_BITS
DOWNLOAD_FILES_CMD = b"\x0b" + DONT_CARE_BITS
BREAK_SUSPEND_CMD = b"\x14" + DONT_CARE_BITS
DELETE_FILE_CMD = b"\x0c" + DONT_CARE_BITS

# Masks
NULL_DATA_MSK = int("01000000", 2)
FIELD_TYPE_MSK = int("00110000", 2)
SETT_CHANGED_MSK = int("00000010", 2)
SIGN_MSK = int("00001000", 2)
DECIMAL_PLACE_MSK = int("00000111", 2)
